name: CI-CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: |
          cd TestContainerizedApp
          dotnet restore

      - name: Build
        run: | 
          cd TestContainerizedApp
          dotnet build --no-restore -c Release

      - name: Test
        run: |
          # Add tests if you have them. Placeholder
          echo "No tests configured"